version: 0.1
phases:
  install:
    commands:
      - echo installing credstash
      - pip install credstash
  pre_build:
    commands:
      - echo Logging in to Docker Hub....
      - docker login --username="$(credstash -r us-west-2 get dockercloud.username)" --password="$(credstash -r us-west-2 get dockercloud.password)"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f $DOCKERFILE_LOCATION -t $ORG_NAME/$IMAGE_NAME:$IMAGE_TAG .
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ORG_NAME/$IMAGE_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo $ACTIVITY_ID
      - echo
